import z from 'zod';
import { Schema, model } from 'mongoose';

const validateForm = z.object({
    Jenis: z.enum(['Q3', 'Q5']),
    E14: z.string().trim().describe("jabatan pemohon"),
    E15: z.string().trim().describe("nama pemohon"),
    E16: z.string().trim().describe("telefon pemohon"),
    E17: z.string().trim().email().describe("emel pemohon#email"),
    M14: z.string().trim().optional().describe("jabatan pegawai"),
    M15: z.string().trim().optional().describe("nama pegawai"),
    M16: z.string().trim().optional().describe("telefon pegawai"),
    M17: z.string().trim().email().optional().describe("emel pegawai#email"),
    E21: z.string().trim().min(1).describe("nama program"),
    E22: z.string().trim().optional().describe("jumlah peserta"),
    M21: z.string().trim().optional().describe("tarikh mula"),
    M22: z.string().trim().optional().describe("tarikh akhir"),
    M23: z.string().trim().optional().describe("masa seminar"),
    F27: z.string().trim().optional().describe("tarikh masuk"),
    F28: z.string().trim().optional().describe("tarikh keluar"),
    F30: z.string().trim().optional().describe("bilik perseorangan (HOD) L"),
    H30: z.string().trim().optional().describe("bilik perseorangan (HOD) P"),
    N30: z.string().trim().optional().describe("bilik berkongsi berdua L"),
    P30: z.string().trim().optional().describe("bilik berkongsi berdua P"),
    D31: z.string().trim().optional().describe("catatan"),
    E39: z.string().trim().optional().describe("bilik kuliah"),
    E40: z.string().trim().optional().describe("bilik bengkel"),
    E41: z.string().trim().optional().describe("bilik seminar"),
    E42: z.string().trim().optional().describe("makmal komputer"),
    E43: z.string().trim().optional().describe("dewan rempah ratus"),
    E45: z.string().trim().optional().describe("lain-lain (nyatakan)"),
    I39: z.string().trim().optional().describe("classroom"),
    I40: z.string().trim().optional().describe("cluster"),
    I41: z.string().trim().optional().describe("u-shape"),
    I42: z.string().trim().optional().describe("fishbone"),
    I43: z.string().trim().optional().describe("theatre"),
    I45: z.string().trim().optional().describe("lain-lain (nyatakan)"),
    O39: z.string().trim().optional().describe("lcd projector"),
    O40: z.string().trim().optional().describe("PA (cordless/collar mic)"),
    O41: z.string().trim().optional().describe("portable PA (TOA)"),
    O42: z.string().trim().optional().describe("bateri (AAA,AAA)"),
    O43: z.string().trim().optional().describe("flip chart stand"),
    O44: z.string().trim().optional().describe("A4 paper"),
    O45: z.string().trim().optional().describe("kertas mahjong"),
    O46: z.string().trim().optional().describe("alat tulis"),
    O47: z.string().trim().optional().describe("lain-lain (nyatakan)"),
    D47: z.string().trim().optional().describe("catatan"),
    G52: z.string().trim().optional().describe("kod material"),
    G53: z.string().trim().optional().describe("GL kod"),
    G54: z.string().trim().optional().describe("pusat kos"),
    G55: z.string().trim().optional().describe("bajet makan minum yang diluluskan"),
    G56: z.string().trim().optional().describe("catatan"),
    C59: z.string().trim().optional().describe("tarikh"),
    F59: z.string().transform(val => Number(val)).optional().describe("sarapan"),
    H59: z.string().transform(val => Number(val)).optional().describe("minum pagi"),
    J59: z.string().transform(val => Number(val)).optional().describe("makan tengahari"),
    L59: z.string().transform(val => Number(val)).optional().describe("minum petang"),
    N59: z.string().transform(val => Number(val)).optional().describe("makan malam"),
    P59: z.string().transform(val => Number(val)).optional().describe("minum malam"),
    C60: z.string().trim().optional().describe("tarikh"),
    F60: z.string().transform(val => Number(val)).optional().describe("sarapan"),
    H60: z.string().transform(val => Number(val)).optional().describe("minum pagi"),
    J60: z.string().transform(val => Number(val)).optional().describe("makan tengahari"),
    L60: z.string().transform(val => Number(val)).optional().describe("minum petang"),
    N60: z.string().transform(val => Number(val)).optional().describe("makan malam"),
    P60: z.string().transform(val => Number(val)).optional().describe("minum malam"),
    C61: z.string().trim().optional().describe("tarikh"),
    F61: z.string().transform(val => Number(val)).optional().describe("sarapan"),
    H61: z.string().transform(val => Number(val)).optional().describe("minum pagi"),
    J61: z.string().transform(val => Number(val)).optional().describe("makan tengahari"),
    L61: z.string().transform(val => Number(val)).optional().describe("minum petang"),
    N61: z.string().transform(val => Number(val)).optional().describe("makan malam"),
    P61: z.string().transform(val => Number(val)).optional().describe("minum malam"),
    C62: z.string().trim().optional().describe("tarikh"),
    F62: z.string().transform(val => Number(val)).optional().describe("sarapan"),
    H62: z.string().transform(val => Number(val)).optional().describe("minum pagi"),
    J62: z.string().transform(val => Number(val)).optional().describe("makan tengahari"),
    L62: z.string().transform(val => Number(val)).optional().describe("minum petang"),
    N62: z.string().transform(val => Number(val)).optional().describe("makan malam"),
    P62: z.string().transform(val => Number(val)).optional().describe("minum malam"),
    C63: z.string().trim().optional().describe("tarikh"),
    F63: z.string().transform(val => Number(val)).optional().describe("sarapan"),
    H63: z.string().transform(val => Number(val)).optional().describe("minum pagi"),
    J63: z.string().transform(val => Number(val)).optional().describe("makan tengahari"),
    L63: z.string().transform(val => Number(val)).optional().describe("minum petang"),
    N63: z.string().transform(val => Number(val)).optional().describe("makan malam"),
    P63: z.string().transform(val => Number(val)).optional().describe("minum malam"),
    C64: z.string().trim().optional().describe("tarikh"),
    F64: z.string().transform(val => Number(val)).optional().describe("sarapan"),
    H64: z.string().transform(val => Number(val)).optional().describe("minum pagi"),
    J64: z.string().transform(val => Number(val)).optional().describe("makan tengahari"),
    L64: z.string().transform(val => Number(val)).optional().describe("minum petang"),
    N64: z.string().transform(val => Number(val)).optional().describe("makan malam"),
    P64: z.string().transform(val => Number(val)).optional().describe("minum malam"),
    C65: z.string().trim().optional().describe("tarikh"),
    F65: z.string().transform(val => Number(val)).optional().describe("sarapan"),
    H65: z.string().transform(val => Number(val)).optional().describe("minum pagi"),
    J65: z.string().transform(val => Number(val)).optional().describe("makan tengahari"),
    L65: z.string().transform(val => Number(val)).optional().describe("minum petang"),
    N65: z.string().transform(val => Number(val)).optional().describe("makan malam"),
    P65: z.string().transform(val => Number(val)).optional().describe("minum malam"),
    C67: z.string().trim().optional().describe("tarikh"),
    F67: z.string().transform(val => Number(val)).optional().describe("sahur"),
    H67: z.string().transform(val => Number(val)).optional().describe("buka puasa"),
    J67: z.string().transform(val => Number(val)).optional().describe("moreh"),
    C68: z.string().trim().optional().describe("tarikh"),
    F68: z.string().transform(val => Number(val)).optional().describe("sahur"),
    H68: z.string().transform(val => Number(val)).optional().describe("buka puasa"),
    J68: z.string().transform(val => Number(val)).optional().describe("moreh"),
    C69: z.string().trim().optional().describe("tarikh"),
    F69: z.string().transform(val => Number(val)).optional().describe("sahur"),
    H69: z.string().transform(val => Number(val)).optional().describe("buka puasa"),
    J69: z.string().transform(val => Number(val)).optional().describe("moreh"),
    C70: z.string().trim().optional().describe("tarikh"),
    F70: z.string().transform(val => Number(val)).optional().describe("sahur"),
    H70: z.string().transform(val => Number(val)).optional().describe("buka puasa"),
    J70: z.string().transform(val => Number(val)).optional().describe("moreh"),
    C71: z.string().trim().optional().describe("tarikh"),
    F71: z.string().transform(val => Number(val)).optional().describe("sahur"),
    H71: z.string().transform(val => Number(val)).optional().describe("buka puasa"),
    J71: z.string().transform(val => Number(val)).optional().describe("moreh"),
    E74: z.string().trim().optional().describe("dome set"),
    K74: z.string().trim().optional().describe("vegetarian"),
    D76: z.string().trim().optional().describe("catatan"),
});

type IForm = z.infer<typeof validateForm>;

const formSchema = new Schema<IForm>({
    Jenis: { type: String, required: true },
    E14: { type: String, required: true },
    E15: { type: String, required: true },
    E16: { type: String, required: true },
    E17: { type: String, required: true },
    M14: { type: String },
    M15: { type: String },
    M16: { type: String },
    M17: { type: String },
    E21: { type: String, required: true },
    E22: { type: String },
    M21: { type: String },
    M22: { type: String },
    M23: { type: String },
    F27: { type: String },
    F28: { type: String },
    F30: { type: String },
    H30: { type: String },
    N30: { type: String },
    P30: { type: String },
    D31: { type: String },
    E39: { type: String },
    E40: { type: String },
    E41: { type: String },
    E42: { type: String },
    E43: { type: String },
    E45: { type: String },
    I39: { type: String },
    I40: { type: String },
    I41: { type: String },
    I42: { type: String },
    I43: { type: String },
    I45: { type: String },
    O39: { type: String },
    O40: { type: String },
    O41: { type: String },
    O42: { type: String },
    O43: { type: String },
    O44: { type: String },
    O45: { type: String },
    O46: { type: String },
    O47: { type: String },
    D47: { type: String },
    G52: { type: String },
    G53: { type: String },
    G54: { type: String },
    G55: { type: String },
    G56: { type: String },
    C59: { type: String },
    F59: { type: String },
    H59: { type: String },
    J59: { type: String },
    L59: { type: String },
    N59: { type: String },
    P59: { type: String },
    C60: { type: String },
    F60: { type: String },
    H60: { type: String },
    J60: { type: String },
    L60: { type: String },
    N60: { type: String },
    P60: { type: String },
    C61: { type: String },
    F61: { type: String },
    H61: { type: String },
    J61: { type: String },
    L61: { type: String },
    N61: { type: String },
    P61: { type: String },
    C62: { type: String },
    F62: { type: String },
    H62: { type: String },
    J62: { type: String },
    L62: { type: String },
    N62: { type: String },
    P62: { type: String },
    C63: { type: String },
    F63: { type: String },
    H63: { type: String },
    J63: { type: String },
    L63: { type: String },
    N63: { type: String },
    P63: { type: String },
    C64: { type: String },
    F64: { type: String },
    H64: { type: String },
    J64: { type: String },
    L64: { type: String },
    N64: { type: String },
    P64: { type: String },
    C65: { type: String },
    F65: { type: String },
    H65: { type: String },
    J65: { type: String },
    L65: { type: String },
    N65: { type: String },
    P65: { type: String },
    C67: { type: String },
    F67: { type: String },
    H67: { type: String },
    C68: { type: String },
    F68: { type: String },
    H68: { type: String },
    C69: { type: String },
    F69: { type: String },
    H69: { type: String },
    C70: { type: String },
    F70: { type: String },
    H70: { type: String },
    C71: { type: String },
    F71: { type: String },
    H71: { type: String },
    E74: { type: String },
    K74: { type: String },
    D76: { type: String },
});

const Form = model('Form', formSchema);

export type { IForm };
export { Form, validateForm };
